# Generated by Django 3.1 on 2021-07-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_remove_newsletter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
