# Generated by Django 3.1 on 2020-09-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200922_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='yt',
            new_name='ig',
        ),
    ]
