# Generated by Django 3.1 on 2020-09-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200922_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='ig',
            new_name='yt',
        ),
    ]
